name: Node.js CI

on: [push]

jobs:
  build:
    name: Deploy
    steps:
    - name: Setup Postgres
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -R
