name: Node.js CI

on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v1
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: 11
          postgresql db: boxso_test
          postgresql user: postgres
          postgresql password: postgres
      - name: Teste de pasta
        working-directory: ./
        run: ls
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
      - name: Running migrations
        working-directory: ./backend
        run: npx knex migrate:latest
      - name: Run Tests
        working-directory: ./backend
        run: npm test
