name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: harmon758/postgresql-action@v1

    container: node:10
    steps:
      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm install
      - name: Run tests
        working-directory: ./backend
        run: npm test

  # test:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [10.x]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: ls
  #     working-directory: ./backend
  #     run: ls
  #     run: npm ci
  #     run: npm run build --if-present
  #     run: npm test
