name: Node.js CI

on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
      - name: Create Database
        working-directory: ./backend
        run: echo "teste"
      - name: Running migrations
        working-directory: ./backend
        run: npx knex migrate:latest
      - name: Run Tests
        working-directory: ./backend
        run: npm test
